language: python
arch:
  - amd64
  - ppc64le
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
  - pip install .

script: pytest

after_success:
  - codecov
